### PR TITLE
Problems routes

### PR DESCRIPTION
**Pull request by brok3turtl3**
Final Commit!!

### CODE REVIEW

**Review by joie-zhang — APPROVED** [review]
AMAZING work!!!

**Review by sifulsidd — APPROVED** [review]
Good work, routes functioning as intended!

**Review by Ericesposito — APPROVED** [review]
Amazing work everybody!

**Review by paglenn — APPROVED** [review]

**Comment by brok3turtl3** [comment]
Nice work everyone!

**Pull request merged**
